# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
  workflow_dispatch: 
   inputs: 
      deployment_target:
      description: Choose target
      required: true
      default: smoke
      type: choice
      options:
        - smoke
        - regression

jobs:
  test:
    strategy:
      matrix:
        configuration: [Debug]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

        # Execute Smoke tests in the solution
    - name: Execute Smoke tests
      if: "github.event.inputs.deployment_target == 'smoke'"
      run: dotnet test --filter Category=Smoke
      id: smoke

       # Execute Regression tests in the solution
    - name: Execute Regression tests
      if: "github.event.inputs.deployment_target == 'regression'"
      run: dotnet test --filter Category=Regression
      id: regression
    
    # Execute all unit tests in the solution
    - name: Execute unit tests
      if: steps.smoke.conclusion == 'skipped' && steps.regression.conclusion == 'skipped'
      run: dotnet test   

    - name: Load test report history
      uses: actions/checkout@v3
      if: always()
      continue-on-error: true
      with:
        ref: gh_pages
        path: gh_pages

    - name: Build test report
      uses: simple-elf/allure-report-action@v1.7
      if: always()
      with:
        gh_pages: gh_pages
        allure_history: allure-history
        allure_results: bin/Debug/net8.0/allure-results

    - name: Publish test report
      uses: peaceiris/actions-gh-pages@v3
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh_pages
        publish_dir: allure-history